# docker-compose.yml
services:
  fashionconstruct:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8081}  #ЛОКАЛЬНО
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8081}
    restart: unless-stopped
    container_name: fashionconstruct-admin